### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by AdamYLiang** [saphknight/SlackClone-Name-Pending#2]
**Users**
- [x] Keep track of DM channels in it's own separate key 
- [x] User only needs `channel_id` and possibly `dm_id` since we already keep track of respective messages and workspaces in the state
- [x] Should only hold onto the foreign keys of the logged in user 

Everything else looks good! Let me know if you have any questions or want to talk about the state!

**Comment by saphknight** [comment]
* Made a separate key for `direct_messages` in our state. 
* Removed `user_ids` from `channels` because we will only need `workspace_id` to get the users. 
* Removed `direct_message?` boolean flag from our state under `channels`
* removed `messageIds` and `workspaceIds` from `users`
* only showing `channel_ids` for the current user

**Comment by AdamYLiang** [comment]
Nice work!
